### PR TITLE
[SLM] Add support for RWKV6 model 

### PR DESCRIPTION
**Pull request by Celve**
This PR adds RWKV6 support and tokenizer for RWKV vocab.

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks @Celve , do you mind cross checking the serving layer support ?

**Comment by Celve** [comment]
> Thanks @Celve , do you mind cross checking the serving layer support ?

Happy to cross-check the serving layer. Could I have some instructions on how to test serving mode?

**Comment by Kartik14** [comment]
Hi @Celve you can test the serving layer using the following commands:

1.) First start a server:
`python -m mlc_llm.serve.server --model MODEL --model-lib-path MODEL_LIB_PATH `

e.g.:

`python -m mlc_llm.serve.server --model ./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/ --model-lib-path dist/Llama-2-7b-chat-hf-q4f16_1-MLC/Llama-2-7b-chat-hf-q4f16_1-cuda.so`


2.) Send a request to the server using the following script:
```python
import requests

# Get a response using a prompt without streaming
payload = {
   "model": "./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/",
   "messages": [
      {"role": "user", "content": "Hello! Our project is MLC LLM."},
      {
            "role": "assistant",
            "content": "Hello! It's great to hear about your project, MLC LLM.",
      },
      {"role": "user", "content": "What is the name of our project?"},
   ],
   "stream": False,
   # "n": 1,
   "max_tokens": 300,
}
r = requests.post("http://127.0.0.1:8080/v1/chat/completions", json=payload)
choices = r.json()["choices"]
for choice in choices:
   print(f"{choice['message']['content']}\n")
```

You can find more details [here](https://llm.mlc.ai/docs/deploy/rest.html)

**Comment by Celve** [comment]
> Hi @Celve you can test the serving layer using the following commands:
> 
> 1.) First start a server: `python -m mlc_llm.serve.server --model MODEL --model-lib-path MODEL_LIB_PATH `
> 
> e.g.:
> 
> `python -m mlc_llm.serve.server --model ./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/ --model-lib-path dist/Llama-2-7b-chat-hf-q4f16_1-MLC/Llama-2-7b-chat-hf-q4f16_1-cuda.so`
> 
> 2.) Send a request to the server using the following script:
> 
> ```python
> import requests
> 
> # Get a response using a prompt without streaming
> payload = {
>    "model": "./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/",
>    "messages": [
>       {"role": "user", "content": "Hello! Our project is MLC LLM."},
>       {
>             "role": "assistant",
>             "content": "Hello! It's great to hear about your project, MLC LLM.",
>       },
>       {"role": "user", "content": "What is the name of our project?"},
>    ],
>    "stream": False,
>    # "n": 1,
>    "max_tokens": 300,
> }
> r = requests.post("http://127.0.0.1:8080/v1/chat/completions", json=payload)
> choices = r.json()["choices"]
> for choice in choices:
>    print(f"{choice['message']['content']}\n")
> ```
> 
> You can find more details [here](https://llm.mlc.ai/docs/deploy/rest.html)

Thank you for the guidance. I'll proceed with the verification based on these instructions.

**Comment by MasterJH5574** [comment]
CC @Hzfengsy would you mind taking a look at your convenience?

**Comment by Hzfengsy** [comment]
This PR looks good for the non-serve interface. I suggest we can make it merge for now and would follow up for the serving part soon

**Comment by scottorly** [comment]
@tqchen @Celve How do we use this with `convert_weight`?

**Comment by Hzfengsy** [comment]
@scottorly Please try use https://huggingface.co/RWKV/rwkv-6-world-1b6 as original repo.

**Pull request merged**
