### PR TITLE
[Model] Add support for GPTJ architecture

### PR DESCRIPTION
**Pull request by tlopex**
This PR supports GPTJ architecture.

The model conversation demonstration is here:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ mlc_llm chat dist/gpt-j-6b-q4f16_1-MLC              --device "cuda:0" --overrides context_window_size=2048              --model ./dist/libs/gpt-j-6b-q4f16_1-cuda.so
[2024-11-04 21:35:57] INFO auto_device.py:79: Found device: cuda:0
[2024-11-04 21:35:57] INFO engine_base.py:143: Using library model: ./dist/libs/gpt-j-6b-q4f16_1-cuda.so
[21:35:58] /home/tlopex/mlc-llm/cpp/serve/config.cc:688: Under mode "local", max batch size will be set to 4, max KV cache token capacity will be set to 2048, prefill chunk size will be set to 2048. 
[21:35:58] /home/tlopex/mlc-llm/cpp/serve/config.cc:688: Under mode "interactive", max batch size will be set to 1, max KV cache token capacity will be set to 2048, prefill chunk size will be set to 2048. 
[21:35:58] /home/tlopex/mlc-llm/cpp/serve/config.cc:688: Under mode "server", max batch size will be set to 128, max KV cache token capacity will be set to 20800, prefill chunk size will be set to 2048. 
[21:35:58] /home/tlopex/mlc-llm/cpp/serve/config.cc:769: The actual engine mode is "interactive". So max batch size is 1, max KV cache token capacity is 2048, prefill chunk size is 2048.
[21:35:58] /home/tlopex/mlc-llm/cpp/serve/config.cc:774: Estimated total single GPU memory usage: 5395.686 MB (Parameters: 3247.127 MB. KVCache: 1008.268 MB. Temporary buffer: 1140.291 MB). The actual usage might be slightly larger than the estimated number.
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out stats of last request (token/sec)
  /metrics            print out full engine metrics
  /reset              restart a fresh chat
  /set [overrides]    override settings in the generation config. For example,
                      `/set temperature=0.5;top_p=0.8;seed=23;max_tokens=100;stop=str1,str2`
                      Note: Separate stop words in the `stop` option with commas (,).
  Multi-line input: Use escape+enter to start a new line.

>>> hi
How may I help you?
```

I found that I have to change code in `position_embedding` of `relax` to run locally. I wonder if I still need a update there.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
@tlopex Thanks! Do you mind fixing the lint errors as shown in CI?

**Comment by MasterJH5574** [comment]
@tlopex It looks to me that we will need to first send the positional embedding changes to apache/tvm in the file https://github.com/apache/tvm/blob/main/python/tvm/relax/frontend/nn/llm/position_embedding.py. Could you try send your changes to `position_embedding.py` there? After we merge the PR there we can bump tvm and follow up on this PR.

**Comment by tlopex** [comment]
@MasterJH5574 Sure, I've already done that. Please take a look at it: https://github.com/apache/tvm/pull/17506
I am just wondering why it could not pass the CI.

**Comment by MasterJH5574** [comment]
@tlopex Hey sorry for the late response. I might have fixed the CI. Could you please help rebase this branch? We can see if it can pass CI now.

**Comment by tlopex** [comment]
Okay. Thanks! @MasterJH5574

**Comment by tlopex** [comment]
I think it can be merged. Thanks so much!
cc @MasterJH5574 @tqchen

**Review by MasterJH5574 — APPROVED** [review]

**Pull request merged**
