### PR TITLE
[Python] Enable "thrust" for CUDA by default

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR enables thrust for CUDA targets so that we can dispatch some operators (e.g., cumsum) to thrust.

### CODE REVIEW

**Comment by MasterJH5574** [comment]
Depending on https://github.com/apache/tvm/pull/16665, or otherwise dlight error might happen with thrust dispatch.

**Comment by vinx13** [comment]
cc @yongwww

**Comment by yongwww** [comment]
good to have this!

**Comment by MasterJH5574** [comment]
Actually also depending on the MLC CUDA package build. Still working on building the wheel with thrust enabled.

**Comment by srikanthsrnvs** [comment]
How do I use Thrust? I keep getting warnings that "TVM is compiled with thrust but not used during the SLM workflow for Mixtral -- which is supposed to use Thrust for the Top-K routing

**Comment by vinx13** [comment]
@srikanthsrnvs If you build tvm. with `USE_THRUST` on in `config.cmake`, after this PR it should be enabled automatically.
@MasterJH5574 We should also update `gen_cmake_config` for this

**Comment by srikanthsrnvs** [comment]
I did that, but I still get the error: Warning: TVM is built with THRUST but not used

This error occurs when going through the SLM compilation workflow for Mixtral

Srikanth
________________________________

**Comment by vinx13** [comment]
@srikanthsrnvs not sure why it happened, can you check the `target` here is expected? https://github.com/apache/tvm/blob/main/python/tvm/contrib/thrust.py#L24
this PR adds `thrust` to `target.libs`

**Review by tqchen — APPROVED** [review]

**Comment by srikanthsrnvs** [comment]
> @srikanthsrnvs not sure why it happened, can you check the `target` here is expected? https://github.com/apache/tvm/blob/main/python/tvm/contrib/thrust.py#L24 this PR adds `thrust` to `target.libs`

Tested this with breakpoints, the target.libs array is empty

**Comment by MasterJH5574** [comment]
@srikanthsrnvs Thank you for sharing the details! You compile the model with manual target (the large dict in the command), so could you try add `"libs": ["thrust"]` to the dict? On the other hand it's interesting to me that `detect_target_and_host` is never called..

**Comment by srikanthsrnvs** [comment]
> @srikanthsrnvs Thank you for sharing the details! You compile the model with manual target (the large dict in the command), so could you try add `"libs": ["thrust"]` to the dict? On the other hand it's interesting to me that `detect_target_and_host` is never called..

I did this, and got strange results. Without Thrust, here is my tokens/s on Mixtral (uses top-k sort which is good for thrust):
`/home/truffle/models/dolphin-2.7-mixtral-8x7b/quantized/q4f16_2:  input=16 output=256 prefill_time 1.270 sec, prefill_rate 12.6 tokens/sec, decode_time 13.061 sec, decode_rate 19.6 tokens/sec`

With thrust:
`/home/truffle/models/dolphin-2.7-mixtral-8x7b/quantized/q4f16_2:  input=16 output=256 prefill_time 1.270 sec, prefill_rate 12.8 tokens/sec, decode_time 13.161 sec, decode_rate 19.2 tokens/sec`

**Pull request merged**
