### PR TITLE
[SLM] Support ft quantization in all SLM models

### PR DESCRIPTION
**Pull request by rickzx**
Related to: https://github.com/mlc-ai/mlc-llm/issues/1780

Tested on Phi, Stable-LM and Qwen models

### CODE REVIEW

**Review by CharlieFRuan — APPROVED** [review]
LGTM, thank you!

**Comment by Hzfengsy** [comment]
Thank you for the great work. BTW, could we enable `q4f16_ft` in CI pipeline?

https://github.com/mlc-ai/mlc-llm/blob/c30348a10eabff5b27a5f5a40370af9796890a2d/tests/python/integration/test_model_compile.py#L62-L68

**Comment by dusty-nv** [comment]
@rickzx q4f16_ft in SLM workflow is now working for me with StableLM, however Phi-2 has this error:

```bash
mlc_chat convert_weight models/phi-2  --quantization q4f16_ft --output phi-2-q4f16_ft'

[2024-02-20 05:24:36] INFO auto_config.py:115: Found model configuration: models/phi-2/config.json
[2024-02-20 05:24:38] INFO auto_device.py:76: Found device: cuda:0
[2024-02-20 05:24:40] INFO auto_device.py:85: Not found device: rocm:0
[2024-02-20 05:24:41] INFO auto_device.py:85: Not found device: metal:0
[2024-02-20 05:24:43] INFO auto_device.py:85: Not found device: vulkan:0
[2024-02-20 05:24:45] INFO auto_device.py:85: Not found device: opencl:0
[2024-02-20 05:24:45] INFO auto_device.py:33: Using device: cuda:0
[2024-02-20 05:24:45] INFO auto_weight.py:70: Finding weights in: models/phi-2
[2024-02-20 05:24:45] INFO auto_weight.py:136: Not found Huggingface PyTorch
[2024-02-20 05:24:45] INFO auto_weight.py:143: Found source weight format: huggingface-safetensor. Source configuration: models/phi-2/model.safetensors.index.json
[2024-02-20 05:24:45] INFO auto_weight.py:106: Using source weight configuration: models/phi-2/model.safetensors.index.json. Use `--source` to override.
[2024-02-20 05:24:45] INFO auto_weight.py:110: Using source weight format: huggingface-safetensor. Use `--source-format` to override.
[2024-02-20 05:24:45] INFO auto_config.py:153: Found model type: phi. Use `--model-type` to override.
Weight conversion with arguments:
  --config          models/phi-2/config.json
  --quantization    FTQuantize(name='q4f16_ft', kind='ft-quant', quantize_dtype='int4', storage_dtype='int8', model_dtype='float16', group_size=None, num_elem_per_storage=2, max_int_value=7)
  --model-type      phi
  --device          cuda:0
  --source          models/phi-2/model.safetensors.index.json
  --source-format   huggingface-safetensor
  --output          phi-2-q4f16_ft
[2024-02-20 05:24:45] INFO phi_model.py:50: context_window_size not found in config.json. Falling back to max_position_embeddings (2048)
Traceback (most recent call last):
  File "/usr/local/bin/mlc_chat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/__main__.py", line 28, in main
    cli.main(sys.argv[2:])
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/cli/convert_weight.py", line 87, in main
    convert_weight(
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/interface/convert_weight.py", line 169, in convert_weight
    _convert_args(args)
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/interface/convert_weight.py", line 68, in _convert_args
    model, quantize_map = args.model.quantize[args.quantization.kind](
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/model/phi/phi_quantization.py", line 37, in ft_quant
    model = quantization.quantize_model(
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/quantization/ft_quantization.py", line 162, in quantize_model
    model = mutator.visit(name_prefix, model)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/visitor.py", line 140, in visit
    setattr(node, key, self.visit_module(_get_child_name(name, key), value))
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/quantization/ft_quantization.py", line 158, in visit_module
    return self.visit(name, node)
  File "/usr/local/lib/python3.10/dist-packages/tvm/relax/frontend/nn/visitor.py", line 140, in visit
    setattr(node, key, self.visit_module(_get_child_name(name, key), value))
  File "/usr/local/lib/python3.10/dist-packages/mlc_chat/quantization/ft_quantization.py", line 133, in visit_module
    or (self.config.quantize_dtype == "int4" and node.out_features % 8 != 0)
TypeError: not all arguments converted during string formatting
```

**Comment by dusty-nv** [comment]
@rickzx @CharlieFRuan I was able to get Phi-2 working with q4f16_ft quantization with the following patch, and it raised my tokens/sec from 31 -> 72 (on AGX Orin)

```diff
diff --git a/python/mlc_chat/model/phi/phi_model.py b/python/mlc_chat/model/phi/phi_model.py
index 421876d..4f56976 100644
--- a/python/mlc_chat/model/phi/phi_model.py
+++ b/python/mlc_chat/model/phi/phi_model.py
@@ -286,7 +286,7 @@ class PhiCausalLMHead(nn.Module):
         super().__init__()
 
         self.ln = nn.LayerNorm(config.n_embd, eps=config.layer_norm_epsilon)
-        self.linear = nn.Linear(config.n_embd, "vocab_size")
+        self.linear = nn.Linear(config.n_embd, config.vocab_size)
 
     def forward(self, hidden_states: Tensor):
         hidden_states = self.ln(hidden_states)
@@ -300,7 +300,7 @@ class PhiCausalLMHead(nn.Module):
 class PhiModel(nn.Module):
     def __init__(self, config: PhiConfig) -> None:
         super().__init__()
-        self.embd = nn.Embedding("vocab_size", config.n_embd)
+        self.embd = nn.Embedding(config.vocab_size, config.n_embd)
         self.h = nn.ModuleList([PhiParallelBlock(config) for i in range(config.n_layer)])
         self.tensor_parallel_shards = config.tensor_parallel_shards
```

I am not sure this is the appropriate fix, because other mlc_chat models like llama are able to refer to config variables as string names, but for some reasons phi-2 is not.

**Comment by CharlieFRuan** [comment]
@dusty-nv Apologies for the late response. https://github.com/mlc-ai/mlc-llm/pull/1849 should fix it.

**Pull request merged**
