### PR TITLE
[Slim-LM] Enable loading from AWQ pre-quantized weight.

### PR DESCRIPTION
**Pull request by LeshengJin**
Enable loading from AWQ pre-quantized weight.

### CODE REVIEW

**Comment by zxybazh** [comment]
Hi Lesheng, could you please fix the linting? And is this ready for review?

**Comment by LeshengJin** [comment]
Thanks @zxybazh for the review. It's not ready yet.

**Comment by junrushao** [comment]
Please rebase to the latest HEAD

**Review by zxybazh — APPROVED** [review]
LGTM, thanks @LeshengJin for enabling AWQ support!

**Review by cyx-6 — APPROVED** [review]
LGTM!

**Pull request merged**
