### PR TITLE
[KVCache]Migrate Qwen2 model to PagedKVCache

### PR DESCRIPTION
**Pull request by tlopex**
This PR migrates Qwen2 model to the new PagedKVCache interface.
Screenshot
image

### CODE REVIEW

**Review by tqchen — APPROVED** [review]

**Comment by tqchen** [comment]
Thanks @tlopex can you confirm mlc serve?

**Comment by tlopex** [comment]
@tqchen Sure! Because there are still some problems I encountered when started MLC serve. After going through them, I'll test models one by one.

**Comment by alphaarea** [comment]
I'm not sure if this is a bug or not, but my attempts to run q4f16_1 quantized Qwen1.5-72B prompts for out of memory. Even if I limit context-window-size to 1024 it doesn't run.

My hardware works fine running llama2-70b and supports 4096 context-window-size, why does qwen2 need so much memory?

```log
[2024-03-10 09:51:51] INFO auto_device.py:33: Using device: cuda:0
[2024-03-10 09:51:51] INFO chat_module.py:373: Using model folder: /home/alphaarea/models/Qwen1.5-72B-q4f16_1
[2024-03-10 09:51:51] INFO chat_module.py:374: Using mlc chat config: /home/alphaarea/models/Qwen1.5-72B-q4f16_1/mlc-chat-config.json
[2024-03-10 09:51:51] INFO chat_module.py:516: Using library model: /home/alphaarea/models/Qwen1.5-72B-q4f16_1/Qwen1.5-72B-q4f16_1-cuda.so
[2024-03-10 09:51:52] INFO model_metadata.py:96: Total memory usage: 42192.77 MB (Parameters: 38782.77 MB. KVCache: 2560.00 MB. Temporary buffer: 850.00 MB)
[2024-03-10 09:51:52] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
[09:51:55] /workspace/mlc-llm/cpp/loader/multi_gpu_loader.cc:133: [Worker #0] Loading model to device: cuda:0
[09:51:55] /workspace/mlc-llm/cpp/loader/multi_gpu_loader.cc:133: [Worker #1] Loading model to device: cuda:1
[09:51:55] /workspace/mlc-llm/cpp/loader/multi_gpu_loader.cc:133: [Worker #2] Loading model to device: cuda:2
[09:51:55] /workspace/mlc-llm/cpp/loader/multi_gpu_loader.cc:133: [Worker #3] Loading model to device: cuda:3
[09:51:55] /workspace/mlc-llm/cpp/loader/multi_gpu_loader.cc:158: Loading parameters...
Traceback (most recent call last):=====>                                                            ]  [345/885]
...
InternalError: Check failed: (e == cudaSuccess || e == cudaErrorCudartUnloading) is false: CUDA: out of memory
Aborted (core dumped)
```

## Environment

 - Platform: CUDA
 - Operating system: Ubuntu 22.04.3 LTS (5.15.0-91-generic)
 - Device: Tesla P100 16G x4
 - How you installed MLC-LLM: `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu121 mlc-ai-nightly-cu121`
 - How you installed TVM-Unity: `python3 -m pip install --pre -U -f https://mlc.ai/wheels mlc-chat-nightly-cu121 mlc-ai-nightly-cu121`
 - Python version: 3.11
 - GPU driver version: 545.23.08
 - CUDA/cuDNN version: 12.1

**Comment by tlopex** [comment]
@alphaarea Thanks for your question!
This is just a guess, but it seems like the Qwen1.5-72B model has higher memory requirements compared to the llama2-70b model you've successfully run. This could be due to the inherent design and larger parameter size of the Qwen1.5-72B model. One immediate step you can take is to further reduce the context_window_size. Even though you've already tried limiting it to 1024, consider reducing it even more to see if that helps mitigate the memory issue.

**Comment by tlopex** [comment]
Here is the test of MLC serve.

My test_server_rest_api.py
```
# test_server_rest_api.py
import requests
import json

model = "dist/Qwen1.5-0.5B-q4f16_1-MLC"
port = 8000
payload = {
    "model": f"{model}",
    "messages": [{"role": "user", "content": "Can you tell me a joke of an ancient king?"}],
    "stream": False,
}

r = requests.post(f"http://127.0.0.1:{port}/v1/chat/completions", json=payload)
if r.status_code != 200:
    print(r.json())
else:
    print(r.json()["choices"][0]["message"]["content"])
```

The response:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python test_server_rest_api.py 
Why did the king become lonely? He lived in a palace that was easy to see in....
```

MLC serve running and status:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python -m mlc_chat.serve.server --model dist/Qwen1.5-0.5B-q4f16_1-MLC --model-lib-path ./dist/libs/Qwen1.5-0.5B-q4f16_1-cuda.so
[2024-03-10 19:39:38] INFO auto_device.py:76: Found device: cuda:0
[2024-03-10 19:39:39] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-10 19:39:39] INFO auto_device.py:85: Not found device: metal:0
[2024-03-10 19:39:40] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-10 19:39:40] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-10 19:39:40] INFO auto_device.py:33: Using device: cuda:0
[2024-03-10 19:39:40] INFO chat_module.py:373: Using model folder: /home/tlopex/mlc-llm/dist/Qwen1.5-0.5B-q4f16_1-MLC
[2024-03-10 19:39:40] INFO chat_module.py:374: Using mlc chat config: /home/tlopex/mlc-llm/dist/Qwen1.5-0.5B-q4f16_1-MLC/mlc-chat-config.json
[2024-03-10 19:39:40] INFO chat_module.py:516: Using library model: ./dist/libs/Qwen1.5-0.5B-q4f16_1-cuda.so
[2024-03-10 19:39:42] INFO engine.py:240: Estimated KVCacheConfig "max_total_sequence_length": 135114.
[2024-03-10 19:39:42] INFO engine.py:245: Estimated total single GPU memory usage: 14504.99 MB (Parameters: 332.53 MB. KVCache: 12731.37 MB. Temporary buffer: 1441.08 MB)
INFO:     Started server process [9371]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:55524 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by alphaarea** [comment]
@tlopex 
I tried q3f16_1 quantization directly and set context_window_size=512. but still ran out of video memory

Memory usage info at compile:  
`[2024-03-10 13:48:02] INFO model_metadata.py:96: Total memory usage: 32762.76 MB (Parameters: 31057.76 MB. KVCache: 1280.00 MB. Temporary buffer: 425.00 MB)`

If that's what the Qwen models are, then I'll have to add more GPU

**Comment by alphaarea** [comment]
@tlopex 

As I tried different sizes of qwen2 models I realized that qwen2 still doesn't support tensor parallel to split the model. When setting `--tensor-parallel-shard 4`, it still loads the full model into each card.

Are there any plans to support this feature?

**Comment by tqchen** [comment]
@tlopex we should followup to enable TP for related models

**Comment by tlopex** [comment]
@alphaarea Thanks for your report! I'm willing to support that in the future.
@tqchen Sure, I'll try to enable TP for those related models.

**Comment by tqchen** [comment]
also cc @MasterJH5574 @DiegoCao @CharlieFRuan for TP enablement checklist

**Pull request merged**
