### PR TITLE
[Fix] mistral `max_gen_len`

### PR DESCRIPTION
**Pull request by davidpissarra**
This PR fixes a bug with `max_gen_len` for the mistral-based models. #1249 introduced customizable `max_gen_len` based on the config's `max_sequence_length`, but mistral used to ignore `max_sequence_length` and this argument was set to -1. Consequently `max_gen_len` would also be set to -1 and the model would not generate outputs. As suggested in the Mistral paper, `max_sequence_length` can be set as `sliding_window * 4`.

### CODE REVIEW

**Comment by davidpissarra** [comment]
cc @CharlieFRuan

**Review by junrushao — APPROVED** [review]
Looks good! Thanks for the update!

**Comment by CharlieFRuan** [comment]
Might need to update `llm_chat.cc` accordingly, taking a look now

**Comment by CharlieFRuan** [comment]
Thank you for the catch!

The reason why I am a bit hesitant is that, though we set `max_sequence_length` here, it does not get used anywhere, so it seems a bit unsafe to me (i.e. we do not dump it to `mlc-chat-config`, do not use it from `metadatafunc`, so `max_seq_len` is completely unused in runtime). I am worried that by setting it to non `-1`, we may introduce error silently in future.

How about we manually set `max_gen_len` for SWA models, since that is our sole purpose for now:
https://github.com/mlc-ai/mlc-llm/blob/77a4b69b44a98bac603b021e187f6cf0fa44a66c/mlc_llm/core.py#L691-L694
Adding `config["max_gen_len"] = args.sliding_window * 4`.

Let me know your thoughts! @junrushao @davidpissarra

**Comment by junrushao** [comment]
Either way seems good to me as long as we got a reasonable default value for `max_gen_len`

**Comment by CharlieFRuan** [comment]
Discussed with @davidpissarra offline; we can consider adding a `max_sequence_length` for SWA models in runtime as well (instead of having an "infinite" context window, limit it to, say, `4 * sliding_window`). This also unify SWA and non-SWA models runtime logic a bit

**Comment by davidpissarra** [comment]
We can perhaps work on a better solution in a near future when unifying max_sequence_length with sliding_window 🙂

**Pull request merged**
