### PR TITLE
fix llm_chat.cc rwkv bug

### PR DESCRIPTION
**Pull request by BBuf**
I successfully ran the rwkv-world-3b fp16 model on my Xiaomi phone. This PR is to fix a bug on the main branch where the rwkv model outputs only one word and then stop.

图片

### CODE REVIEW

**Comment by junrushao** [comment]
CC: @MasterJH5574

**Comment by tqchen** [comment]
Thanks @BBuf can you fix the clang-format lint, then we can merge this in

**Comment by BBuf** [comment]
> Thanks @BBuf can you fix the clang-format lint, then we can merge this in

How can I request ci again?

**Comment by junrushao** [comment]
Looks like there’s still some clang-format thing left over

**Comment by BBuf** [comment]
> Looks like there’s still some clang-format thing left over

It should be okay now. Could you please trigger the CI again?

**Comment by junrushao** [comment]
Thanks a bunch! @BBuf its good to merge now!

**Review by junrushao — APPROVED** [review]

**Pull request merged**
