### PR TITLE
[Docs] Introductory tutorial

### PR DESCRIPTION
**Pull request by MasterJH5574**
This PR updates the documentation with an introduction turorial. The landing page now directs to the quick start page and the tutorial.

### CODE REVIEW

**Comment by tlopex** [comment]
Hi,@MasterJH5574 
I found that there is no updated Chinese version intro doc of MLC-LLM on online platforms like Zhihu, 
if you don't mind, I can write a version of that.

**Comment by tqchen** [comment]
@tlopex you are more than welcome to do that

**Comment by tlopex** [comment]
@tqchen Thanks, I'll do that as soon as possible.

**Comment by tqchen** [comment]
We are still in the process of v0.5 refactoring, so things can still change in next two weeks. Maybe let us focus on making the current english docs polished in the coming few weeks, then we can do that

**Comment by tlopex** [comment]
Got it. Let me know if everything is already.

**Comment by tlopex** [comment]
@tqchen Hi, I‘ve done and uploaded simple Chinese version of intro doc to Zhihu. 
Tell me if anything need to be changed or added.
The article here: https://zhuanlan.zhihu.com/p/697647183

**Pull request merged**
