### PR TITLE
[BugFix] Add annotated decode type check for FuseDecodeTake

### PR DESCRIPTION
**Pull request by L0phTg**
type of annotated decode may be 'expr.DataflowVar'

### CODE REVIEW

**Comment by L0phTg** [comment]
in this case, type of lv4 is `DataflowVar`:
```python
@R.function
def prefill(input_ids,...):
    ...
    with R.dataflow():
        lv4 = R.call_tir(cls.rms_norm, (lv2, lv409), out_sinfo=R.Tensor((1, n, 768), dtype="float16"))
        lv5: R.Tensor((1, n, 768), dtype="float16") = lv4
	lv48 = R.call_tir(cls.NT_matmul2, (lv5, lv539), out_sinfo=R.Tensor((1, n, 768), dtype="float16"))
    ...
```

**Review by MasterJH5574 — APPROVED** [review]
Thanks @L0phTg for the enhancement! I would like to learn more about the case you encountered. Could I ask which model you built has this?
```python
lv5: R.Tensor((1, n, 768), dtype="float16") = lv4
```

**Comment by L0phTg** [comment]
> 

I'm trying to support T5 pretrained model

**Comment by jparismorgan** [comment]
Just checked and this actually fixes this issue as well! https://github.com/mlc-ai/mlc-llm/issues/457#issuecomment-1632220370

**Pull request merged**
