### PR TITLE
Fix gen_mlc_chat_config for mistral 

### PR DESCRIPTION
**Pull request by jinhongyii**
Add sliding_window and prefill_chunk_size in chat config

### CODE REVIEW

**Comment by jinhongyii** [comment]
cc: @junrushao

**Comment by CharlieFRuan** [comment]
Thank you for the fix! Will review it first thing tomorrow

**Review by davidpissarra — APPROVED** [review]
lgtm @CharlieFRuan @jinhongyii

**Comment by CharlieFRuan** [comment]
That makes sense to me, but I thought we still wanted to provide the prebuilt model libraries? It seems that in the workflow you suggested we compile the model during runtime.

**Pull request merged**
