### PR TITLE
[SLM] Add support for Qwen model

### PR DESCRIPTION
**Pull request by rickzx**
This PR introduces Qwen model (https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py) support using the new nn.Module compilation pipeline. Qwen is a large language model family built by Alibaba Cloud.

```
build/mlc_chat_cli --model models/Qwen-7B-Chat-q4f16_1/params --model-lib-path /ssd1/rickzhou/rick_fork/binary-mlc-llm-libs/Qwen-7B-Chat-q4f16_1-cuda.so
Use MLC config: "/ssd1/rickzhou/rick_fork/mlc-llm/models/Qwen-7B-Chat-q4f16_1/params/mlc-chat-config.json"
Use model weights: "/ssd1/rickzhou/rick_fork/mlc-llm/models/Qwen-7B-Chat-q4f16_1/params/ndarray-cache.json"
Use model library: "/ssd1/rickzhou/rick_fork/binary-mlc-llm-libs/Qwen-7B-Chat-q4f16_1-cuda.so"
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /reload [model]  reload model `model` from disk, or reload the current model if `model` is not specified

Loading model...
Loading finished
Running system prompts...
System prompts finished
<|im_start|>user: 请为我写一首关于春天的诗          
<|im_start|>assistant: 春天是一年四季中最美的季节，它充满了生机和活力。在这个季节里，万物复苏，树木发芽，花朵盛开，鸟儿歌唱。春天的空气清新，阳光明媚，让人感觉温暖舒适。春天是大自然的赞歌，它提醒我们欣赏生活中的美好，享受每一刻的快乐。
以下是我为你创作的一首关于春天的诗：
春风吹过山野间，
万物复苏显生机。
花开满树红似火，
鸟语声声乐曲鸣。
阳光明媚照人心，
温暖舒适如梦乡。
春天美景在眼前，
让我们心怀感恩情。
春天是大自然的赞歌，
提醒我们欣赏生活中的美好。
让我们珍惜每一刻，
享受生活的每一秒。
春天的美好永流传，
让我们一起唱出春天的歌！
希望这首诗能让你感受到春天的美好，也希望你能喜欢它。如果你有任何其他问题或需要帮助，请随时告诉我。
<|im_start|>user: Translate it to English
<|im_start|>assistant: Spring breeze blows through the mountains and fields,
All things revive, full of vitality.
The flowers bloom on the trees red like fire,
Bird songs sound, music notes sing.
The sunshine is bright, warm in the heart,
Comfortable as a dreamland.
The beauty of spring is in front of us,
Let's be grateful with a kind heart.
Enjoy every moment, enjoy every second,
The beauty of life is eternal.
Spring is the song of nature's praise,
Reminding us to appreciate the beauty of life.
Let's cherish every moment,
Enjoy every second of life.
The beauty of spring will last forever,
Let's sing out the song of spring together!
I hope this poem can make you feel the beauty of spring, and I also hope you like it. If you have any other questions or need help, please tell me at any time        
<|im_start|>user: 
```

### CODE REVIEW

**Review by junrushao — APPROVED** [review]
Awesome! This looks great!

**Comment by junrushao** [comment]
Hey @rickzx, would you like to also include model configuration into our model presets, so that they are tested in the CI? https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/model/model_preset.py

**Comment by MingkangW** [comment]
`git clone https://www.modelscope.cn/qwen/Qwen-1_8B-Chat.git`
`python -m mlc_chat convert_weight [model-path] --quantization q4f16_1-o [output-model-path]`
`python -m mlc_chat gen_config [model-path] --quantization q4f16_1 --conv-template qwen -o [output-model-path]`
`python -m mlc_chat compile [output-model-path]/mlc-chat-config.json --device cuda -o [lib-path]` 
hey @rickzx , I compiled the Qwen model with the above command, but it was prompted that there was no qwen in the conv_template when I ran the gen_config. I added qwen to the CONV_TEMPALTES of python/mlc_chat/interface/gen_config.py, but when I inferenced the model, I got a message "Cannot find any tokenizer under: dist/Qwen-1_8B-Chat". How can I solve this problem?

**Comment by CharlieFRuan** [comment]
Hi @MingkangW make sure you clone from huggingface https://huggingface.co/Qwen/Qwen-1_8B-Chat

**Comment by CharlieFRuan** [comment]
If `dist/Qwen-1_8B-Chat` is your `output-model-path` in `convert_weight`, make sure you use the same path for `gen_config`, so that the `mlc-chat-config.json` and tokenizer files are in this folder as well.

**Comment by MingkangW** [comment]
@CharlieFRuan The path is the same, but when gen_config, there is no `tokenizer. json` file generated like other models, such as the official tutorial `RedPajama-INCITE-Chat-3B-v1`, which contains `tokenizer. json` in the original model, but Qwen does not. I do not know how to generate Qwen's `tokenizer.json` file.

**Comment by ningpengtao-coder** [comment]
@MingkangW https://huggingface.co/Qwen/Qwen-tokenizer.download it.copy it to quantized model directory.

**Comment by ningpengtao-coder** [comment]
@rickzx Qwen 2 beta is released, consider supporting it?

**Pull request merged**
