### PR TITLE
[Rest] Fix emoji handling in Rest API.

### PR DESCRIPTION
**Pull request by YuchenJin**
Fixing issue #804. I adopted @WanderingMeow's fix, and verified it works well!

Co-authored-by: WanderingMeow <128711250+wanderingmeow@users.noreply.github.com>

### CODE REVIEW

**Comment by junrushao** [comment]
Thanks @YuchenJin! Copy @spectrometerHBH as i dont now much about the emoji handling

**Comment by tqchen** [comment]
Thanks @YuchenJin , do you mind format the file with black?

**Comment by YuchenJin** [comment]
> Thanks @YuchenJin , do you mind format the file with black?

Sure, just formatted.

**Comment by junrushao** [comment]
Curious what this mysterious character means 😆

**Comment by tqchen** [comment]
cc @Kartik14 @MasterJH5574 @davidpissarra

**Comment by YuchenJin** [comment]
> Curious what this mysterious character means 😆

� is a replacement character ([U+FFFD](https://www.fileformat.info/info/unicode/char/fffd/index.htm)). This issue arises because an emoji might be made up of multiple tokens. In the Rest streaming setting, if an emoji gets truncated in the middle of its encoded byte sequence, this character will appear.

**Comment by junrushao** [comment]
Got it! Thanks for sharing this info!

**Comment by tqchen** [comment]
great @YuchenJin , do you mind send a pr with followup to document this note?

**Comment by YuchenJin** [comment]
> great @YuchenJin , do you mind send a pr with followup to document this note?

Yep, #1160 is up!

**Pull request merged**
