### PR TITLE
[SLM] Android update Model Record Fields

### PR DESCRIPTION
**Pull request by Kartik14**
This PR updates the model record field in android to match with IOS and webllm.

### CODE REVIEW

**Review by CharlieFRuan — COMMENTED** [review]
One nit on vram estimation. Everything else looks great. Thank you!

**Comment by Kartik14** [comment]
@CharlieFRuan Updated the vram values in `app-config.json` and made `model_path` and `estimatedVramBytes` fields optional. Also, the code automatically reads the model parameters (`chunk_size`, `context_window`) automatically from the metadata.

**Comment by CharlieFRuan** [comment]
Thank you! LGTM. Except I think we are missing a vram for `Llama-2-7b-chat-hf-q4f16_1` :)

**Comment by Kartik14** [comment]
> Thank you! LGTM. Except I think we are missing a vram for `Llama-2-7b-chat-hf-q4f16_1` :)

Ohh yeah, added it! Thanks for catching that.

**Review by CharlieFRuan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
