### PR TITLE
[Android] Add Qwen2 support

### PR DESCRIPTION
**Pull request by mengshyu**
cc @tqchen

### CODE REVIEW

**Comment by BlindDeveloper** [comment]
@tqchen 
Hello, please rebuild android demo app for include this model.

**Comment by tqchen** [comment]
@BlindDeveloper i think this is already included? cc @mengshyu

**Comment by mengshyu** [comment]
Hi @BlindDeveloper Just confirmed the latest Android demo app includes Qwen2. Could you check it again? Thanks.
https://llm.mlc.ai/docs/deploy/android.html

**Comment by BlindDeveloper** [comment]
@mengshyu 
Thank you!

**Pull request merged**
