### PR TITLE
Refactor android project into a library and application module

### PR DESCRIPTION
**Pull request by tobrun**
This is a follow up to https://github.com/mlc-ai/mlc-llm/issues/361. 
This project decouples the android project into two parts:
 - application module: 
   - example app implementation with UI elements
 - library module: 
   - minimum parts to get a LLM working in an Android library.
 
The issue that this PR addresses is that we weren't able to cleanly use mlc-llm inside another application. It was tightly coupled with the UI of the app and wasn't in a format that other applications can use (apk application format vs aar library format). 

This change also unblocks publishing prebuild versions of the library to maven. So in the future app developers could add the following to their build script:
> implementation "ai.mlc.mlcllm.Llama-2-7b-chat-hf-q4f16_0"

and sideload the model weights.

Additionally, I also made the root of the Android project (settings.gradle/build.gradle) directly available in the /android directory.

This PR is a first pass and can be improved upon. For example, `./prepare-libs` needs to be called before building the project (which is status-quo on current implementation) but ideally we move as part of the gradle build system. 

Happy to hear any feedback or address any changes.

### CODE REVIEW

**Comment by cyx-6** [comment]
The proposal and PR looks great. It would be perfect if you could start a tracking issue for the incoming refactoring PRs, including the current one. So we may have a preview of the overall plan. Also, could you please help update the doc for android after all refactor is done?

**Comment by tobrun** [comment]
>  The proposal and PR looks great. It would be perfect if you could start a tracking issue for the incoming refactoring PRs, including the current one. So we may have a preview of the overall plan. 

Tracking these issues in:
https://github.com/mlc-ai/mlc-llm/issues/1295
https://github.com/mlc-ai/mlc-llm/issues/1296

> update the doc for android after all refactor is done

I would prefer doing this incrementally which each PR, will try finding some time this week to make the changes.

**Comment by cyx-6** [comment]
@tobrun Thanks for updating! Shall we merge this PR first, or you will have some updates on this PR?

**Comment by tobrun** [comment]
I checked the docs and not seeing anything that needs updating (tracking general addition of docs in https://github.com/mlc-ai/mlc-llm/issues/1383). I think we are good to merge this PR if :+1: from your end.

**Comment by cyx-6** [comment]
Thanks for updating! If I understand correctly, there will be some follow-up PRs to improve the `build.gradle`? While this PR focuses on the file structure refactor, and seeting up the base `build.gradle` for further PRs.

**Comment by tobrun** [comment]
> Thanks for updating! If I understand correctly, there will be some follow-up PRs to improve the build.gradle? While this PR focuses on the file structure refactor, and seeting up the base build.gradle for further PRs.

Yes, optimizing the build is independent of the objective for this PR (which was to decouple the project into a library and application module)

**Comment by cyx-6** [comment]
Thanks for your contribution and patience over review. Looking forward to the upcoming PRs :)

**Pull request merged**
