### PR TITLE
[Doc]  fix-missing-code-block of `Download OpenCL ICD loader and manually add libmali to ICD` section

### PR DESCRIPTION
**Pull request by day253**
fix typo of #784

the view of document

image

the Origininal rst

image

### CODE REVIEW

**Comment by day253** [comment]
@Hzfengsy

**Comment by Hzfengsy** [comment]
cc @Chrisz236

**Comment by day253** [comment]
Ping @Hzfengsy @Chrisz236

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
Sorry for the late response, and thanks for the fix

**Comment by day253** [comment]
> Sorry for the late response, and thanks for the fix

Thx!

**Comment by day253** [comment]
image

The document is ok.

**Pull request merged**
