### PR TITLE
Support system message to fix https://github.com/mlc-ai/mlc-llm/issue…

### PR DESCRIPTION
**Pull request by kripper**
Add AutoGen support using the MLC REST API.

### CODE REVIEW

**Comment by louis030195** [comment]
i need this too to integrate in:

https://github.com/stellar-amenities/assistants


can we merge?

**Comment by tqchen** [comment]
please fix the pylint error

**Comment by kripper** [comment]
> please fix the pylint error

Done.

**Comment by kripper** [comment]
Thanks professor @tqchen and congratulations for your excelente work.
Maybe you are the ideal person to explain if Mistral's rolling buffer KV cache can be used for https://github.com/mlc-ai/mlc-llm/issues/1703

**Pull request merged**
