### PR TITLE
Support Qwen2-MoE Architecture

### PR DESCRIPTION
**Pull request by Hzfengsy**
[Qwen1.5-MoE-A2.7B-Chat](https://huggingface.co/Qwen/Qwen1.5-MoE-A2.7B-Chat) is an open-sourced 14B MoE model, based on Qwen2-MoE architecture. It is possible to run on mobile devices.

Note that we need to support multi-device TP for the arch for future large models. However, I fail to do that because of limited devices.

cc @vinx13 @tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
@DiegoCao can you help to followup and add TP support?

**Comment by Hzfengsy** [comment]
depends on https://github.com/apache/tvm/pull/16848, waiting for the next sync

**Comment by MasterJH5574** [comment]
Just rebased mlc-ai/relax. Let's trigger the CI tomorrow.

**Comment by DiegoCao** [comment]
Got it, working on the TP support

**Comment by Hzfengsy** [comment]
Waiting for dependencies: https://github.com/apache/tvm/pull/16887 and https://github.com/apache/tvm/pull/16886

BTW, there is a known numerical issue on Vulkan. Will fix it in a follow-up PR.

**Comment by tqchen** [comment]
@Hzfengsy seems alll deps are landed, let us followup

**Review by tqchen — APPROVED** [review]

**Pull request merged**
