### PR TITLE
Parameter Loading for New `nn.Module` API

### PR DESCRIPTION
**Pull request by junrushao**
## New Components

This PR introduces `mlc_llm.param_loader` as a new subpackge of MLC LLM compiler, with the following components:

**`ParameterMapping`** that describes how a MLC parameter maps to one or more PyTorch parameters by their names. For example, the MLC parameter `qkv_proj.weight` corresponds to three parameters in PyTorch, which are `q_proj.weight`, `k_proj.weight` and `v_proj.weight`, and to map PyTorch parameters to this MLC parameter, the mapping function is:

```python
lambda q, k, v: np.concatenate([q, k, v], axis=0)
```

**`HFTorchLoader`** that loads HuggingFace's PyTorch parameters in a certain ordering to save peak memory footprint. More specifically, HuggingFace shards the full parameter set into a few `.bin` files of more reasonable size (usually less than 10G each), and the loader fetches them on disk to recover the PyTorch parameters, while unloading some files once not needed.

We implemented `mlc_llm.models.llama_param_map.hf_torch` that returns a `ParameterMapping`, then used by `HFTorchLoader` to convert PyTorch parameters provided by HuggingFace repo to MLC parameters. See the logic in `tests/python/test_param_loader_llama.py` for more details.

## Improvements

Furthermore, we brought up a few improvements along the way:

**ModelConfig** is introduced as a base class to specific model configurations such as `LlamaConfig` to allow more convenient loading of HuggingFace's `config.json` into a dataclass. It provides two class methods `from_dict` and `from_file` that can be used to construct its subclasses. The unused information in `config.json`, e.g. `initializer_range` is not used during inference, will be stored in the `kwargs` field in its subclass.

A few enhancement to the new Llama implementation is also provided:

- Horizontal fusion is introduced as `nn.MultiLinear` (originally by @MasterJH5574);
- Rotary embedding is now "online" - no precomputed sin/cos are used any more, meaning the upper limit of sequence length is removed at least for computation. NOTE: for certain embedding types, it is still limited by model training (originally brought up by @MasterJH5574 and @yzh119).
- Dynamic vocabulary size is supported by symbolic shape (originally by @CharlieFRuan);
- Added a `LlamaForCasualLM.get_default_spec` that allows more in-lined view of the model definition;
- `head_dim` is explicitly added in `LlamaConfig`, which is calculated during `__post_init__` phase of dataclass construction, to avoid re-calculate it everywhere once used. This is particularly useful for building a sharded model when `num_heads` need to be divided across GPU workers (by @junrushao myself).

A few detailed messages are added:
- If a PyTorch parameter is not used during weight conversion, for example, `rotary_emb.inv_freq`, unless explicitly specified, MLC will warn that it is unused;
- If a MLC parameter corresponds to a PyTorch parameter that does not exist in HuggingFace repo, it errors out immediately.

## Coding Style

Coding style in new modules `mlc_llm.param_loader` and `mlc_llm.models`:

- All Python files are formatted with isort and black;
- All Python files are linted with pylint, but not mypy yet;
- `print` is strictly avoided and instead `logging` is used (proposed by @CharlieFRuan).
- All Python APIs are documented unless for those starting with "_";
- Usage of `nn.Module` is now formalized as `nn.ModuleName` for Modules, and `op.op_name` for atomic operators;
- Paths in the file system are explicitly represented using `pathlib.Path` instead of raw strings to avoid potential issues (according to a previous bugfix #671).
- The word `relax` is avoided as possible and replaced with `MLC` or `TVM`, as I would consider `relax` is an implementation detail inside TVM to avoid potential confusion.

## Examples

To show some sample logging messages of parameter loading for Llama:

```
2023-09-20 16:27:18 INFO hf_torch_loader.py:161: Loading PyTorch parameters from: dist/models/llama-2-7b-chat-hf/pytorch_model-00002-of-00002.bin
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.self_attn.q_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.self_attn.k_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.self_attn.v_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.self_attn.o_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.self_attn.rotary_emb.inv_freq", shape: (64,), dtype: torch.float32
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.mlp.gate_proj.weight", shape: (11008, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.mlp.up_proj.weight", shape: (11008, 4096), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.mlp.down_proj.weight", shape: (4096, 11008), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.input_layernorm.weight", shape: (4096,), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.24.post_attention_layernorm.weight", shape: (4096,), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "model.norm.weight", shape: (4096,), dtype: torch.float16
2023-09-20 16:27:20 DEBUG hf_torch_loader.py:173:     Parameter: "lm_head.weight", shape: (32000, 4096), dtype: torch.float16
...
2023-09-20 16:27:31 DEBUG hf_torch_loader.py:178: Unloading PyTorch weight file: dist/models/llama-2-7b-chat-hf/pytorch_model-00002-of-00002.bin
2023-09-20 16:27:32 INFO hf_torch_loader.py:161: Loading PyTorch parameters from: dist/models/llama-2-7b-chat-hf/pytorch_model-00001-of-00002.bin
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.embed_tokens.weight", shape: (32000, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.self_attn.q_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.self_attn.k_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.self_attn.v_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.self_attn.o_proj.weight", shape: (4096, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.self_attn.rotary_emb.inv_freq", shape: (64,), dtype: torch.float32
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.mlp.gate_proj.weight", shape: (11008, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.mlp.up_proj.weight", shape: (11008, 4096), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.mlp.down_proj.weight", shape: (4096, 11008), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.input_layernorm.weight", shape: (4096,), dtype: torch.float16
2023-09-20 16:27:38 DEBUG hf_torch_loader.py:173:     Parameter: "model.layers.0.post_attention_layernorm.weight", shape: (4096,), dtype: torch.float16
...
2023-09-20 16:28:07 DEBUG hf_torch_loader.py:178: Unloading PyTorch weight file: dist/models/llama-2-7b-chat-hf/pytorch_model-00001-of-00002.bin
2023-09-20 16:28:07 INFO hf_torch_loader.py:152: Time used in PyTorch loading: 8.867 sec. Total 12.551 GB loaded
```

### CODE REVIEW

**Comment by zxybazh** [comment]
Nit: `Loadnig` -> `Loading`.

**Comment by junrushao** [comment]
CC: @zxybazh @MasterJH5574 @tqchen

**Review by MasterJH5574 — APPROVED** [review]
Looks good. Thank you @junrushao!

**Comment by junrushao** [comment]
Follow up items:
* Print stats on peak memory usage in the loader
* Support the case where weights are actually **not sharded** as a standalone `pytorch_model.bin` like RedPajama models: https://huggingface.co/togethercomputer/RedPajama-INCITE-Chat-3B-v1/tree/main

**Pull request merged**
