### PR TITLE
Reorganize folder structure

### PR DESCRIPTION
**Pull request by junrushao**
This PR reorganizes the existing `python/` folder structure for better clarify.

- `mlc_chat/model` <- `mlc_chat/compiler/model`
- `mlc_chat/quantization` <- `mlc_chat/compiler/quantization`
- `mlc_chat/loader` <- `mlc_chat/compiler/loader`
- `mlc_chat/operator` <- `mlc_chat/compiler/*_op.py`
- `mlc_chat/compiler_pass` <- `mlc_chat/compiler/compiler_pass.py`
- `mlc_chat/interface` <- `mlc_chat/compiler/{compile/gen_config/convert_weight}.py`
- `mlc_chat/runtime` <- `mlc_chat/chat_module.py` and `mlc_chat/callback.py`

### CODE REVIEW

**Comment by Nick-infinity** [comment]
"Operator "is an internal python package which is used in nested imports in mlc_chat python files. "mlc_chat/operator <- mlc_chat/compiler/*_op.py" this change creates a conflict when we try to use the mlc from source by exporting mlc-llm/python to PYTHONPATH

**Comment by junrushao** [comment]
Ah @Nick-infinity thanks for the reminder! Would you love to elaborate what the cycling files are so that i could quickly fix? Thanks a bunch!

**Comment by Nick-infinity** [comment]
Hello,

here is the trace for cyclic dependency

Traceback (most recent call last):
  File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/__main__.py", line 4, in <module>
    from mlc_chat.support import logging
  File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/__init__.py", line 5, in <module>
    from .chat_module import (
  File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/chat_module.py", line 3, in <module>
    import inspect
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/inspect.py", line 35, in <module>
    import ast
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ast.py", line 29, in <module>
    from contextlib import contextmanager, nullcontext
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 5, in <module>
    from collections import deque
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/collections/__init__.py", line 37, in <module>
    from operator import eq as _eq
  File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/operator/__init__.py", line 2, in <module>
    from .attention import attention
  File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/operator/attention.py", line 4, in <module>
    from tvm import tir
  File "/Users/workspace/stacks/mlc-llm/3rdparty/tvm/python/tvm/__init__.py", line 19, in <module>
    import multiprocessing
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/__init__.py", line 16, in <module>
    from . import context
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 3, in <module>
    import threading
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 6, in <module>
    import functools
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 18, in <module>
    from collections import namedtuple
ImportError: cannot import name 'namedtuple' from partially initialized module 'collections' (most likely due to a circular import) (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/collections/__init__.py)




**It starts from this import**

 File "/Users/workspace/stacks/mlc-llm/python/mlc_chat/chat_module.py", line 3, in <module>
    import inspect

**and goes to** 

File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/collections/__init__.py", line 37, in <module>
    from operator import eq as _eq

Now this operator is being picked as mlc_chat operator package from pythonpath instead of system operator package

**Comment by Nick-infinity** [comment]
A simple renaming of mlc_chat operator package fixes it

**Pull request merged**
