### PR TITLE
[KVCache] Migrate Baichuan model to PagedKVCache

### PR DESCRIPTION
**Pull request by tlopex**
This PR migrates Baichuan model to the new PagedKVCache interface.
Result example:
图片

### CODE REVIEW

**Comment by tlopex** [comment]
cc @tqchen

**Comment by tqchen** [comment]
Thank you, can we also test the MLC serve command @MasterJH5574 can send some benchmark pointers

**Comment by tlopex** [comment]
Sorry, but I might not find correct MLC serve commands.
Are commends in `mlc-llm/tests/python/serve/server/test_server.py` like 
"""Server tests in MLC LLM.
Before running any test, we use pytest fixtures to launch a
test-session-wide server in a subprocess, and then execute the tests.

The recommended way to run the tests is to use the following command:
  MLC_SERVE_MODEL_LIB="YOUR_MODEL_LIB" pytest -vv tests/python/serve/server/test_server.py

Here "YOUR_MODEL_LIB" is a compiled model library like
`dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-cuda.so`,
as long as the model is built with batching and embedding separation enabled.

To directly run the Python file (a.k.a., not using pytest), you need to
launch the server in ahead before running this file. This can be done in
two steps:
- start a new shell session, run
  python -m mlc_chat.serve.server --model "YOUR_MODEL_LIB"
- start another shell session, run this file
  MLC_SERVE_MODEL_LIB="YOUR_MODEL_LIB" python tests/python/serve/server/test_server.py
"""
?

**Comment by MasterJH5574** [comment]
Hi @tlopex, thank you for the contribution! Let me prepare an example for you tomorrow. Prior to that, as of now to run Baichuan model in MLC serve, we will need to register the ChatML conversation template (which Baichuan uses) into this file https://github.com/mlc-ai/mlc-llm/blob/ac57c03ccc1ec8e9d8079d6577c5c135dd80bec0/python/mlc_chat/conversation_template.py#L37-L38.

Would you like to register the template? Basically It should be as simple as copying these lines from `conv_templates.cc` https://github.com/mlc-ai/mlc-llm/blob/ac57c03ccc1ec8e9d8079d6577c5c135dd80bec0/cpp/conv_templates.cc#L10-L29
into the Python file and make few syntactical changes accordingly. Happy to help and answer any question you have.

**Comment by tlopex** [comment]
@MasterJH5574 Okay, I'm willing to do that!

**Comment by MasterJH5574** [comment]
Hi @tlopex, after thinking a bit, I find this gist might be helpful to get you started with testing MLC serve. https://gist.github.com/MasterJH5574/ea1ba901938338a27434c18cdcd3f935

It takes the Mixtral model as an example, but the flow is applicable to any model, including Baichuan.

Feel free to skip the preparation part and `gen_config`/`convert_weight`/`compile` part if you have already done them. Please let me know if there's any issue! I'm very happy to help you through and get the server support for Baichuan.

**Comment by tlopex** [comment]
@MasterJH5574 Hi! Thanks for your template review and instructions. I followed your instructions but got wrong.
Here is the error:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python -m mlc_chat.serve.server --model dist/Baichuan2-7B-Chat-q4f16_1-MLC --model-lib-path ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
[2024-03-01 20:03:49] INFO auto_device.py:76: Found device: cuda:0
[2024-03-01 20:03:49] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-01 20:03:50] INFO auto_device.py:85: Not found device: metal:0
[2024-03-01 20:03:50] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-01 20:03:51] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-01 20:03:51] INFO auto_device.py:33: Using device: cuda:0
[2024-03-01 20:03:51] INFO chat_module.py:373: Using model folder: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC
[2024-03-01 20:03:51] INFO chat_module.py:374: Using mlc chat config: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-03-01 20:03:51] INFO chat_module.py:516: Using library model: ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/server/__main__.py", line 56, in <module>
    args: argparse.Namespace = parse_args_and_initialize()
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/server/__main__.py", line 46, in parse_args_and_initialize
    engine = async_engine.AsyncThreadedEngine(
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/async_engine.py", line 130, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/engine.py", line 173, in _estimate_max_total_sequence_length
    num_kv_heads = model_config["num_key_value_heads"]
KeyError: 'num_key_value_heads'
```
Some models like Baichuan do not have the config `num_key_value_heads`, and I do not know a better way to modify the code, like adding a conditional statement or something. So I report it to you.

**Comment by tlopex** [comment]
I 'm glad to offer help if you need any :)

**Comment by MasterJH5574** [comment]
Hey @tlopex, just want to give you an update. Hopefully #1888 can address the config name issue.

**Comment by tqchen** [comment]
@tlopex can you followup?

**Comment by tlopex** [comment]
@tqchen Absolutely! I'll validate Baichuan and Stablelm today.
@MasterJH5574  Thanks!

**Comment by tlopex** [comment]
@MasterJH5574 
Hi, I tried same commands you mentioned in your instructions but got
```
python -m mlc_chat.serve.server --model dist/Baichuan2-7B-Chat-q4f16_1-MLC --model-lib-path ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
[2024-03-05 12:45:58] INFO auto_device.py:76: Found device: cuda:0
[2024-03-05 12:45:59] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-05 12:45:59] INFO auto_device.py:85: Not found device: metal:0
[2024-03-05 12:46:00] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-05 12:46:00] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-05 12:46:00] INFO auto_device.py:33: Using device: cuda:0
[2024-03-05 12:46:00] INFO chat_module.py:373: Using model folder: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC
[2024-03-05 12:46:00] INFO chat_module.py:374: Using mlc chat config: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-03-05 12:46:00] INFO chat_module.py:516: Using library model: ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tlopex/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 194, in <module>
    main()
  File "/home/tlopex/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 188, in main
    _print_kv_cache_metadata_in_json(metadata)
  File "/home/tlopex/mlc-llm/python/mlc_chat/cli/model_metadata.py", line 125, in _print_kv_cache_metadata_in_json
    print(json.dumps(metadata["kv_cache"]))
KeyError: 'kv_cache'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/server/__main__.py", line 56, in <module>
    args: argparse.Namespace = parse_args_and_initialize()
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/server/__main__.py", line 46, in parse_args_and_initialize
    engine = async_engine.AsyncThreadedEngine(
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/async_engine.py", line 151, in __init__
    kv_cache_config.max_total_sequence_length = _estimate_max_total_sequence_length(
  File "/home/tlopex/mlc-llm/python/mlc_chat/serve/engine.py", line 176, in _estimate_max_total_sequence_length
    kv_cache_metadata_str = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'mlc_chat.cli.model_metadata', './dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so', '--print-kv-cache-metadata-in-json']' returned non-zero exit status 1.
```
The script failed with a KeyError when attempting to access the 'kv_cache' key within a dictionary. It appears that this key is expected to exist within the metadata dictionary but is missing. This error occurs in the mlc_chat/cli/model_metadata.py script.
Additionally, a CalledProcessError was raised when a subprocess command was executed. The command aimed to gather model metadata but returned a non-zero exit status, indicating failure. This occurred in the mlc_chat/serve/server/__main__.py script.
The errors were same for both Baichuan and Stablelm.

**Comment by MasterJH5574** [comment]
Ah you may need to recompile the model with `mlc_chat compile`, since the metadata is attached when compiling models.

**Comment by tlopex** [comment]
That's strange. I have already recomplied mlc-llm after updating the code.

**Comment by MasterJH5574** [comment]
Could you check if the model compilation runs into this line? https://github.com/mlc-ai/mlc-llm/blob/aeb55f1e721c4b77a3b3bbfc47a193679d2bda08/python/mlc_chat/compiler_pass/rewrite_kv_cache_creation.py#L104

**Comment by tlopex** [comment]
Ohh, I followed commands of #1890 with some additional configs, it seems work.
图片
Is this considered a success?

**Comment by tlopex** [comment]
@MasterJH5574 Sorry that I misunderstood what you said.
I recompiled the model and used the code below to send requests.
```
# test_server_rest_api.py
import requests
import json

model = "./dist/Baichuan2-7B-Chat-q4f16_1-MLC/"
port = 8000
payload = {
    "model": f"{model}",
    "messages": [{"role": "user", "content": "Tell me about a zoo in 200 words."}],
    "stream": False,
}
r = requests.post(f"http://127.0.0.1:{port}/v1/chat/completions", json=payload)
if r.status_code != 200:
    print(r.json())
else:
    print(r.json()["choices"][0]["message"]["content"])
```
But it shows `{"object":"error","message":"The requested model \"./dist/Baichuan2-7B-Chat-q4f16_1-MLC/\" is not served.","code":400}`
How can I handle it? Thanks.

**Comment by MasterJH5574** [comment]
Ah I guess maybe you need to pass `model = "dist/Baichuan2-7B-Chat-q4f16_1-MLC"`. You can send a GET request to `http://127.0.0.1:port/v1/models` to see which model is served. https://github.com/mlc-ai/mlc-llm/blob/2f26e05d4ca1beb006099d0c1f1370a73e0f13ba/tests/python/serve/server/test_server.py#L188

**Comment by tlopex** [comment]
I sent a GET request and got 
```
{'object': 'list', 'data': [{'id': 'dist/Baichuan2-7B-Chat-q4f16_1-MLC', 'created': 1709800696, 'object': 'model', 'owned_by': 'MLC-LLM'}]}

```
but I can't quite understand where should I pass` dist/Baichuan2-7B-Chat-q4f16_1-MLC` to

**Comment by MasterJH5574** [comment]
@tlopex Need to pass it in the `model` below.

```python
# test_server_rest_api.py
import requests
import json

model = "dist/Baichuan2-7B-Chat-q4f16_1-MLC"   # <<<<<  pass it here
port = 8000
payload = {
    "model": f"{model}",
    "messages": [{"role": "user", "content": "Tell me about a zoo in 200 words."}],
    "stream": False,
}
r = requests.post(f"http://127.0.0.1:{port}/v1/chat/completions", json=payload)
if r.status_code != 200:
    print(r.json())
else:
    print(r.json()["choices"][0]["message"]["content"])
```

Another thing I missed is that, you need to add the conversation template of Baichuan to here so that MLC Serve can recognize the conv template https://github.com/mlc-ai/mlc-llm/blob/655ae5c188fd800aaf471cb0453a31ea986b8993/python/mlc_chat/conversation_template.py#L37-L39

We are planning to unify the conversation templates so that they duplicate in both C++ and Python, but for now we still need to add it in Python to support MLC Serve.

**Comment by tlopex** [comment]
Thanks so much! @MasterJH5574 
I tested MLC serve with program above and it is like
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python -m mlc_chat.serve.server --model dist/Baichuan2-7B-Chat-q4f16_1-MLC --model-lib-path ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
[2024-03-08 22:02:51] INFO auto_device.py:76: Found device: cuda:0
[2024-03-08 22:02:52] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-08 22:02:52] INFO auto_device.py:85: Not found device: metal:0
[2024-03-08 22:02:53] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-08 22:02:54] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-08 22:02:54] INFO auto_device.py:33: Using device: cuda:0
[2024-03-08 22:02:54] INFO chat_module.py:373: Using model folder: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC
[2024-03-08 22:02:54] INFO chat_module.py:374: Using mlc chat config: /home/tlopex/mlc-llm/dist/Baichuan2-7B-Chat-q4f16_1-MLC/mlc-chat-config.json
[2024-03-08 22:02:54] INFO chat_module.py:516: Using library model: ./dist/libs/Baichuan2-7B-Chat-q4f16_1-cuda.so
[2024-03-08 22:02:55] INFO engine.py:240: Estimated KVCacheConfig "max_total_sequence_length": 15311.
[2024-03-08 22:02:55] INFO engine.py:245: Estimated total single GPU memory usage: 14504.72 MB (Parameters: 4026.88 MB. KVCache: 7832.56 MB. Temporary buffer: 2645.28 MB)
[22:02:55] /home/tlopex/mlc-llm/cpp/tokenizers.cc:79: Warning: Using `tokenizer.model` since we cannot locate `tokenizer.json`.
It is recommended to use `tokenizer.json` to ensure all token mappings are included, since currently, files like `added_tokens.json`, `tokenizer_config.json` are ignored.
Consider converting `tokenizer.model` to `tokenizer.json` by compiling the model with MLC again, or see if MLC's huggingface provides this file.
[22:02:55] /home/tlopex/mlc-llm/cpp/tokenizers.cc:79: Warning: Using `tokenizer.model` since we cannot locate `tokenizer.json`.
It is recommended to use `tokenizer.json` to ensure all token mappings are included, since currently, files like `added_tokens.json`, `tokenizer_config.json` are ignored.
Consider converting `tokenizer.model` to `tokenizer.json` by compiling the model with MLC again, or see if MLC's huggingface provides this file.
INFO:     Started server process [28997]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:50948 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:42406 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51574 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```
Does it mean that MLC serve looks fine?
On account of that Baichuan model uses ChatML template, I don't need to add template of it.
However, for models like stablelm, I may still need to update the template if I want to test the MLC serve of it.

**Comment by MasterJH5574** [comment]
Yes I think so, thanks for confirming! On the Python side it's also expected that the response makes sense.

**Comment by tlopex** [comment]
@MasterJH5574 Thanks.
This is the response generated:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ python test_server_rest_api.py 
Sure thing :) Here's a joke about ancient dragons: Once upon a time there was an ancient dragon named Zephyr who lived deep within a hidden valley filled with magical plants...
```

And my test_server_rest_api.py is like
```
# test_server_rest_api.py
import requests
import json

model = "dist/Baichuan2-7B-Chat-q4f16_1-MLC"
port = 8000
payload = {
    "model": f"{model}",
    "messages": [{"role": "user", "content": "Can you tell me a joke of an ancient dragon?"}],
    "stream": False,
}

r = requests.post(f"http://127.0.0.1:{port}/v1/chat/completions", json=payload)
if r.status_code != 200:
    print(r.json())
else:
    print(r.json()["choices"][0]["message"]["content"])
```

And the status is still 
`INFO:     127.0.0.1:34450 - "POST /v1/chat/completions HTTP/1.1" 200 OK`
So I think that is fine.

**Comment by MasterJH5574** [comment]
Sounds great, thank you!

**Pull request merged**
