### PR TITLE
[Doc] Update doc for prebuilt models

### PR DESCRIPTION
**Pull request by CharlieFRuan**
Update documentation for prebuilt models, reflecting the current prebuilt we support.

Following up to #752.

### CODE REVIEW

**Comment by CharlieFRuan** [comment]
Hi @Hzfengsy, it would be great if you could cross check for me! The main change is the [Prebuilt for CLI table](https://mlc.ai/mlc-llm/docs/prebuilt_models.html#id8):  
Screen Shot 2023-08-16 at 1 18 46 AM

**Comment by Hzfengsy** [comment]
Thanks for the great work @CharlieFRuan!

The name `Model Series` is a bit confusing to me, which can be explained to be:
1. The original repo of the model
2. The model arch

There are different solutions, either looks good to me:
1. Renaming the `Model Series` to `Original Model`, and provide the links to its original repo (HF or github)
2. Renaming the `Model Series` to `Model Arch` and making all llama-based models (e.g. vicuna, chinese-llama, uncensored-llama) use the same arch `Llama`
3. Keep both two columns of `Original Model` and `Model Arch` as mentioned above.

Also love to hear the opinions from you and the community :)

**Comment by CharlieFRuan** [comment]
@Hzfengsy thanks for the suggestions! I went with `Original Model`; I guess users can see the corresponding architecture in the `Supported Model Architectures` section.
image

**Review by Hzfengsy — APPROVED** [review]

**Comment by Hzfengsy** [comment]
Thanks @CharlieFRuan!

**Pull request merged**
