### PR TITLE
[SLM] Add support for InternLM2 architecture

### PR DESCRIPTION
**Pull request by tlopex**
Thanks for @MasterJH5574 's help, now we can support Internlm2

The model conversation demonstration is shown below:
```
tlopex@tlopex-OMEN-by-HP-Laptop-17-ck1xxx:~/mlc-llm$ mlc_llm chat dist/internlm2-chat-7b-q4f16_1-MLC \
>              --device "cuda:0" --overrides context_window_size=32768 \
>              --model-lib ./dist/libs/internlm2-chat-7b-q4f16_1-cuda.so
[2024-06-26 23:21:47] INFO config.py:106: Overriding context_window_size from None to 32768
[2024-06-26 23:21:50] INFO auto_device.py:79: Found device: cuda:0
[2024-06-26 23:21:50] INFO chat_module.py:379: Using model folder: /home/tlopex/mlc-llm/dist/internlm2-chat-7b-q4f16_1-MLC
[2024-06-26 23:21:50] INFO chat_module.py:380: Using mlc chat config: /home/tlopex/mlc-llm/dist/internlm2-chat-7b-q4f16_1-MLC/mlc-chat-config.json
[2024-06-26 23:21:50] INFO chat_module.py:529: Using library model: ./dist/libs/internlm2-chat-7b-q4f16_1-cuda.so
[2024-06-26 23:21:51] INFO model_metadata.py:96: Total memory usage: 20455.20 MB (Parameters: 4151.20 MB. KVCache: 0.00 MB. Temporary buffer: 16304.00 MB)
[2024-06-26 23:21:51] INFO model_metadata.py:105: To reduce memory usage, tweak `prefill_chunk_size`, `context_window_size` and `sliding_window_size`
[23:21:51] /home/tlopex/mlc-llm/cpp/tokenizers.cc:81: Warning: Using `tokenizer.model` since we cannot locate `tokenizer.json`.
It is recommended to use `tokenizer.json` to ensure all token mappings are included, since currently, files like `added_tokens.json`, `tokenizer_config.json` are ignored.
Consider converting `tokenizer.model` to `tokenizer.json` by compiling the model with MLC again, or see if MLC's huggingface provides this file.
You can use the following special commands:
  /help               print the special commands
  /exit               quit the cli
  /stats              print out the latest stats (token/sec)
  /reset              restart a fresh chat
  /set [overrides]    override settings in the generation config. For example,
                      `/set temperature=0.5;max_gen_len=100;stop=end,stop`
                      Note: Separate stop words in the `stop` option with commas (,).
  Multi-line input: Use escape+enter to start a new line.

<|im_start|>user: hello
<|im_start|>assistant: 
Hello! How can I assist you today?         
<|im_start|>user: Could you please write a poem for CMU?
<|im_start|>assistant: 
Certainly! Here's a short poem for CMU:

CMU, a place of learning,
Where minds are sharp and spirits are burning,
Innovation is the name of the game,
And knowledge is the currency of fame.

From the heart of Pittsburgh,
CMU stands tall,
A beacon of intellect,
For all who would follow.

In the realm of academia,
CMU is a force to be reckoned with,
With cutting-edge research
And a commitment to truth.

So here's to CMU,
A place where dreams come true,
Where the future is bright
And the possibilities are few.
```

However, I found that original cpp conversation template file have been deleted, could you shortly tell me what to do with the newest version so that ChatML template can be used by the model? Thanks. @MasterJH5574

### CODE REVIEW

**Comment by tlopex** [comment]
cc @tqchen @MasterJH5574

**Comment by MasterJH5574** [comment]
Hi @tlopex, the ChatML template is registered here https://github.com/mlc-ai/mlc-llm/blob/d911c60f37d41ed9fe27a49d9c75a51d9081dd34/python/mlc_llm/conversation_template/registry.py#L37-L53

I think we only need to run `mlc_llm gen_config` with the chatml template to make it work with the model.

**Comment by tlopex** [comment]
@MasterJH5574 Thanks! I updated the model with a limit of prefill chunk size and it worked again locally. Please review my code after it passes CI test.

**Comment by MasterJH5574** [comment]
> do you mean that if I want to add a new template of a new model, I can register in this file[mlc-llm/python/mlc_llm/conversation_template/registry.py](https://github.com/mlc-ai/mlc-llm/blob/d911c60f37d41ed9fe27a49d9c75a51d9081dd34/python/mlc_llm/conversation_template/registry.py#L37-L53) directly?

@tlopex yeah that's true.

**Review by MasterJH5574 — APPROVED** [review]

**Comment by MasterJH5574** [comment]
Thank you @tlopex for adding the InternLM2 model! Could we follow up with the multi-GPU support?

**Comment by tlopex** [comment]
@MasterJH5574 Okay, I'll support that in a few days.

**Pull request merged**
